### ISSUE TITLE
Unsized Types

### ISSUE THREAD

**Issue by Dominilk** [Others/shredder#62]
Hi!
I have already read through this discussion: https://github.com/Others/shredder/pull/45 - but for some reason, I can still not put unsized types into GC even though the feature should now be available. (according to the discussion)

Maybe the new version having the unsized types feature is not available on crates.io?

Best regards,
Dominik

**Comment by Dominilk** [comment]
After quickly testing if cloning the repository and adding it as a local dependency to my project, it turns out that the version available on crates.io is not up to date.

Publishing a new version with all the newly added features on crates.io would be awesome, as cloning the repository is not the cleanest solution.

Best regards,
Dominik

**Comment by Others** [comment]
Hi @Dominilk ,

I will try and publish a new version on crates.io soon. However I'd like to get a couple of things done first (create a derive for `Finalize`, improve the README, and create a writeup of what has changed in the new version).

For now, I recommend taking a git dependency on the repository, instead of cloning it locally. You can use this line in your `Cargo.toml`:
```
shredder = { git = "https://github.com/Others/shredder.git" }
```

I'm going to close out this issue. If you notice that there is still not a new published version in a couple weeks, feel free to open a new issue. Also, if you run into any bugs using the version on github, please let me know.

Thanks,
Others
